spring:
  application:
    name: git100

server:
  port: 7550

xxl:
  job:
    admin:
      #addresses: http://d-xxljob.dmsd.tech:8081/job-admin-dev  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
      #addresses: http://192.168.1.4:8080/xxl-job-admin  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
      addresses: http://localhost:8080/xxl-job-admin  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: testJob #xxljob配置的执行器名称，
      ip:              #执行器IP，默认为空表示自动获取IP
      port: 9999       #xxljob配置的端口号，默认为9999
      logpath: /Users/macbook/ideaProject/ideagit/data/xxl-job/jobhandler  #执行器运行日志文件存储磁盘路径 #注意区分本地环境与linux环境
      logretentiondays: -1  #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能
    accessToken: ''    #调度中心通讯TOKEN [选填]：非空时启用



